CREATE TABLE books (ID NUMBER(10) NOT NULL, AUTHOR VARCHAR, ISBN VARCHAR, PRICE NUMBER(10,5), TITLE VARCHAR, PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMBER(19), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN_SEQUENCE', 0)
